pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

brew_formulae:
  - name: kubectl
  - name: derailed/k9s/k9s
  - name: starship
  - name: nvim
  - name: bat
  - name: eza

brew_casks:
  - name: visual-studio-code
  - name: dbeaver-community
  - name: kitty
  - name: 1password
  - name: 1password-cli
  - name: tailscale
  # Media
  - name: obsidian
  - name: spotify
  - name: steam
