pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A


# --- Homebrew config ---
homebrew_installed_Packages:
  - name: kubectl
  - name: derailed/k9s/k9s
  - name: starship
  - name: nvim
  - name: bat
  - name: eza

homebrew_taps: []
homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - name: visual-studio-code
  - name: dbeaver-community
  - name: kitty
  - name: 1password
  - name: 1password-cli
  - name: tailscale
  # Media
  - name: obsidian
  - name: spotify
  - name: steam

# --- Dock config ---
configure_dock: true
dockitems_remove:
  - TV
  - Podcasts
  - Contacts
