---
- name: Configure host
  hosts: localhost

  vars_files:
    - default.config.yaml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - name: Check for Xcode Command Line Tools
      ansible.builtin.command: xcode-select -p
      register: xcode_select_check
      changed_when: false
      failed_when: false
  
    - name: Fail if Xcode Command Line Tools are missing
      ansible.builtin.fail:
        msg: >-
          Xcode Command Line Tools are not installed.
          Install them once (GUI) with: `xcode-select --install`
          Then re-run this playbook.
      when: xcode_select_check.rc != 0

    - import_tasks: tasks/extra-packages.yaml
      tags: ['extra-packages']

    - import_tasks: tasks/ssh-config.yaml
      tags: ['ssh']
